# Dockerfile.neo4j
FROM neo4j:5.15.0-community-bullseye

COPY ./neo4j/neo4j_db_init/schema.cypher /var/lib/neo4j/db_init/
COPY ./neo4j/conf/apoc.conf /var/lib/neo4j/conf/
COPY ./neo4j/conf/neo4j.conf /var/lib/neo4j/conf/
COPY ./neo4j/plugins/apoc-5.15.0-extended.jar /var/lib/neo4j/plugins/

CMD ["neo4j", "start", "--verbose", "&&", "sleep", "10", "&&", "cypher-shell", "-file", "/var/lib/neo4j/db_init/schema.cypher"]